version: 2.1
orbs:
  ruby: circleci/ruby@2.1.3

jobs:
  test:
    docker:
      - image: cimg/ruby:3.1.5
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
      - ruby/rspec-test

workflows:
  version: 2.1
  test:
    jobs:
      - test
